theme: jekyll-theme-minimal
name: Dario
author: Dario Cancelliere
title: Emulator000
show_downloads: true
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
google_analytics: UA-179098698-1
logo: /assets/img/logo.png
description: Passionate Rustacean, Senior PHP Web Developer, Android and C/C++ Developer
job: Software Engineer @ Facile.it
linkedin: https://www.linkedin.com/in/dario-cancelliere-5a388543/
